pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        S3_BUCKET = 'chaithanya-portfolio-web'
        LAMBDA_CONTACT = 'ContactFormSubmissions'
        LAMBDA_VISITOR = 'trackVisitor'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Chaithu-dot/Chaithanya-Portfolio.git'
            }
        }

        stage('Deploy Lambda: Contact Form') {
            steps {
                sh '''
                cd lambda/contact
                zip -r ../../contact.zip lambda_function.py
                cd ../../
                aws lambda update-function-code \
                    --function-name $LAMBDA_CONTACT \
                    --zip-file fileb://contact.zip \
                    --region $AWS_REGION
                '''
            }
        }

         stage('Deploy Lambda: Visitor Logger') {
            steps {
                sh '''
                cd lambda/track
                zip -r ../../visitor.zip lambda_function.py
                cd ../../
                aws lambda update-function-code \
                    --function-name $LAMBDA_VISITOR \
                    --zip-file fileb://visitor.zip \
                    --region $AWS_REGION
                '''
            }
        }

        stage('Upload Frontend to S3') {
            steps {
                sh '''
                aws s3 sync frontend/ s3://$S3_BUCKET --delete
                aws cloudfront create-invalidation \
                    --distribution-id YOUR_DISTRIBUTION_ID \
                    --paths "/*" \
                    --region $AWS_REGION
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
  }
     
